//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicSignatureService {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicSignatureService.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blockchain Technology ähnelt.
        /// </summary>
        public static string Home_BlockchainTechnology {
            get {
                return ResourceManager.GetString("Home_BlockchainTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The digital fingerprint of your signature, together with a timestamp, is stored in a blockchain as unchangeable proof of data consistency.
        ///This means you can trust the signature regardless of the service provider. ähnelt.
        /// </summary>
        public static string Home_BlockchainTechnology_Text {
            get {
                return ResourceManager.GetString("Home_BlockchainTechnology_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Privacy ähnelt.
        /// </summary>
        public static string Home_DataPrivacy {
            get {
                return ResourceManager.GetString("Home_DataPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not upload any documents, only the fingerprint of the file is stored.
        ///This means that you do not have to entrust your confidential documents to a third party, but can send the files directly to your recipients in the usual way. ähnelt.
        /// </summary>
        public static string Home_DataPrivacy_Text {
            get {
                return ResourceManager.GetString("Home_DataPrivacy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die QR Code and URL based ähnelt.
        /// </summary>
        public static string Home_QRbased {
            get {
                return ResourceManager.GetString("Home_QRbased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert QR codes and links into your document as placeholders for signatures.
        ///These can then be used to create and verify signatures.
        ///This allows you to work with your usual tools. ähnelt.
        /// </summary>
        public static string Home_QRbased_Text {
            get {
                return ResourceManager.GetString("Home_QRbased_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Self Sovereign Identities ähnelt.
        /// </summary>
        public static string Home_SSI {
            get {
                return ResourceManager.GetString("Home_SSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application supports identification and authentication using self-sovereign identities.
        ///All compatible DID wallets can be used for this purpose. ähnelt.
        /// </summary>
        public static string Home_SSI_Text {
            get {
                return ResourceManager.GetString("Home_SSI_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We have sent you an email with a confirmation code. Please also check your spam folder. ähnelt.
        /// </summary>
        public static string Info_ConfirmationEMail {
            get {
                return ResourceManager.GetString("Info_ConfirmationEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert the QR code(s) and URLs into your document and save/export your document as the final file. 
        ///            Then select the final file for registering the associated fingerprint. ähnelt.
        /// </summary>
        public static string Info_InserQRs {
            get {
                return ResourceManager.GetString("Info_InserQRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can provide a certificate and a password to sign cryptographically. 
        ///If your are not comfortable uploading your certificate and your password, you can use LIONS Certificates Wallet instead. ähnelt.
        /// </summary>
        public static string Info_Method_Certificate {
            get {
                return ResourceManager.GetString("Info_Method_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can use the certificates wallet to store your certificates and authenticate and sign locally on your device keeping your private key private. ähnelt.
        /// </summary>
        public static string Info_Method_CertWallet {
            get {
                return ResourceManager.GetString("Info_Method_CertWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you choose the authentication method via e-mail, you will receive an e-mail with a confirmation code, that you will have to enter in the next step. If you do not receive a message, please consider checking your spam folder. ähnelt.
        /// </summary>
        public static string Info_Method_EMail {
            get {
                return ResourceManager.GetString("Info_Method_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you have an account for this service, you can verify yourself using your login credentials. ähnelt.
        /// </summary>
        public static string Info_Method_Login {
            get {
                return ResourceManager.GetString("Info_Method_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify a unique name for the document to be registered as far as possible, so that a clear assignment is possible for the recipients. 
        ///                Also specify the number of placeholders required for different signatures for your document. ähnelt.
        /// </summary>
        public static string Info_NewDocument {
            get {
                return ResourceManager.GetString("Info_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account Credentials ähnelt.
        /// </summary>
        public static string Label_AccountCredentials {
            get {
                return ResourceManager.GetString("Label_AccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All my documents ähnelt.
        /// </summary>
        public static string Label_AllMyDocuments {
            get {
                return ResourceManager.GetString("Label_AllMyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blockchain Mapping ID ähnelt.
        /// </summary>
        public static string Label_BlockchainMappingID {
            get {
                return ResourceManager.GetString("Label_BlockchainMappingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certificate ähnelt.
        /// </summary>
        public static string Label_Certificate {
            get {
                return ResourceManager.GetString("Label_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LIONS Certificate Wallet ähnelt.
        /// </summary>
        public static string Label_CertificateWallet {
            get {
                return ResourceManager.GetString("Label_CertificateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check file validity... ähnelt.
        /// </summary>
        public static string Label_CheckFileValidity {
            get {
                return ResourceManager.GetString("Label_CheckFileValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string Label_Confirm {
            get {
                return ResourceManager.GetString("Label_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirmation Code ähnelt.
        /// </summary>
        public static string Label_ConfirmationCode {
            get {
                return ResourceManager.GetString("Label_ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm E-Mail Address ähnelt.
        /// </summary>
        public static string Label_ConfirmEmailAddress {
            get {
                return ResourceManager.GetString("Label_ConfirmEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die copy ähnelt.
        /// </summary>
        public static string Label_Copy {
            get {
                return ResourceManager.GetString("Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document ähnelt.
        /// </summary>
        public static string Label_Document {
            get {
                return ResourceManager.GetString("Label_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Name ähnelt.
        /// </summary>
        public static string Label_DocumentName {
            get {
                return ResourceManager.GetString("Label_DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Documents ähnelt.
        /// </summary>
        public static string Label_Documents {
            get {
                return ResourceManager.GetString("Label_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Certificate ähnelt.
        /// </summary>
        public static string Label_DownloadCert {
            get {
                return ResourceManager.GetString("Label_DownloadCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Signature ähnelt.
        /// </summary>
        public static string Label_DownloadSignature {
            get {
                return ResourceManager.GetString("Label_DownloadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Electronic Signatures ähnelt.
        /// </summary>
        public static string Label_ElectronicSignatures {
            get {
                return ResourceManager.GetString("Label_ElectronicSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string Label_EMail {
            get {
                return ResourceManager.GetString("Label_EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        public static string Label_Filename {
            get {
                return ResourceManager.GetString("Label_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for certificate ähnelt.
        /// </summary>
        public static string Label_ForCertificate {
            get {
                return ResourceManager.GetString("Label_ForCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get started! ähnelt.
        /// </summary>
        public static string Label_GetStarted {
            get {
                return ResourceManager.GetString("Label_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handsign with finger/mouse ähnelt.
        /// </summary>
        public static string Label_HandsignWithFingerMouse {
            get {
                return ResourceManager.GetString("Label_HandsignWithFingerMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hash ähnelt.
        /// </summary>
        public static string Label_Hash {
            get {
                return ResourceManager.GetString("Label_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string Label_ID {
            get {
                return ResourceManager.GetString("Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identity validation method ähnelt.
        /// </summary>
        public static string Label_IdentityValidationMethod {
            get {
                return ResourceManager.GetString("Label_IdentityValidationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in/from Blockchain ähnelt.
        /// </summary>
        public static string Label_InFromBlockchain {
            get {
                return ResourceManager.GetString("Label_InFromBlockchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP Address ähnelt.
        /// </summary>
        public static string Label_IPAddress {
            get {
                return ResourceManager.GetString("Label_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest ähnelt.
        /// </summary>
        public static string Label_Latest {
            get {
                return ResourceManager.GetString("Label_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Documents ähnelt.
        /// </summary>
        public static string Label_MyDocuments {
            get {
                return ResourceManager.GetString("Label_MyDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Document ähnelt.
        /// </summary>
        public static string Label_NewDocument {
            get {
                return ResourceManager.GetString("Label_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string Label_Next {
            get {
                return ResourceManager.GetString("Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of signatures/placeholders ähnelt.
        /// </summary>
        public static string Label_NumberOfSlots {
            get {
                return ResourceManager.GetString("Label_NumberOfSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string Label_Privacy {
            get {
                return ResourceManager.GetString("Label_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die read more... ähnelt.
        /// </summary>
        public static string Label_ReadMore {
            get {
                return ResourceManager.GetString("Label_ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Label_Register {
            get {
                return ResourceManager.GetString("Label_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register fingerprint of file... ähnelt.
        /// </summary>
        public static string Label_RegisterFile {
            get {
                return ResourceManager.GetString("Label_RegisterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign... ähnelt.
        /// </summary>
        public static string Label_Sign {
            get {
                return ResourceManager.GetString("Label_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature ähnelt.
        /// </summary>
        public static string Label_Signature {
            get {
                return ResourceManager.GetString("Label_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To add or check signatures, please use the link or QR code. ähnelt.
        /// </summary>
        public static string Label_SignatureQR_Hint {
            get {
                return ResourceManager.GetString("Label_SignatureQR_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signatures ähnelt.
        /// </summary>
        public static string Label_Signatures {
            get {
                return ResourceManager.GetString("Label_Signatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature URLs/QR-Codes ähnelt.
        /// </summary>
        public static string Label_SignatureUrlsQRs {
            get {
                return ResourceManager.GetString("Label_SignatureUrlsQRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signer data ähnelt.
        /// </summary>
        public static string Label_SignersData {
            get {
                return ResourceManager.GetString("Label_SignersData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign with certificate ähnelt.
        /// </summary>
        public static string Label_SignWithCert {
            get {
                return ResourceManager.GetString("Label_SignWithCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slot ähnelt.
        /// </summary>
        public static string Label_Slot {
            get {
                return ResourceManager.GetString("Label_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timestamp ähnelt.
        /// </summary>
        public static string Label_Timestamp {
            get {
                return ResourceManager.GetString("Label_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validate Signature ähnelt.
        /// </summary>
        public static string Label_ValidateSignature {
            get {
                return ResourceManager.GetString("Label_ValidateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verification Method ähnelt.
        /// </summary>
        public static string Label_VerificationMethod {
            get {
                return ResourceManager.GetString("Label_VerificationMethod", resourceCulture);
            }
        }
    }
}
